//=============================================================================//
// This file is automatically generated. CHANGES WILL BE LOST.
//=============================================================================//
#include "cbase.h"
#include "srcpy.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

using namespace boost::python;

// The init method is in one of the generated files declared
#ifdef _WIN32
extern "C" __declspec(dllexport) PYINIT_DECL(srcbuiltins)();
extern "C" __declspec(dllexport) PYINIT_DECL(_srcbase)();
extern "C" __declspec(dllexport) PYINIT_DECL(_vmath)();
extern "C" __declspec(dllexport) PYINIT_DECL(_filesystem)();
extern "C" __declspec(dllexport) PYINIT_DECL(_animation)();
extern "C" __declspec(dllexport) PYINIT_DECL(_entities)();
extern "C" __declspec(dllexport) PYINIT_DECL(_entitiesmisc)();
extern "C" __declspec(dllexport) PYINIT_DECL(_gameinterface)();
extern "C" __declspec(dllexport) PYINIT_DECL(_gamerules)();
extern "C" __declspec(dllexport) PYINIT_DECL(_utils)();
extern "C" __declspec(dllexport) PYINIT_DECL(_physics)();
extern "C" __declspec(dllexport) PYINIT_DECL(_sound)();
extern "C" __declspec(dllexport) PYINIT_DECL(_particles)();
extern "C" __declspec(dllexport) PYINIT_DECL(materials)();
extern "C" __declspec(dllexport) PYINIT_DECL(_te)();
extern "C" __declspec(dllexport) PYINIT_DECL(_fow)();
extern "C" __declspec(dllexport) PYINIT_DECL(unit_helper)();
extern "C" __declspec(dllexport) PYINIT_DECL(_editorsystem)();
extern "C" __declspec(dllexport) PYINIT_DECL(_steam)();
extern "C" __declspec(dllexport) PYINIT_DECL(_navmesh)();
extern "C" __declspec(dllexport) PYINIT_DECL(_recast)();
extern "C" __declspec(dllexport) PYINIT_DECL(_ndebugoverlay)();
extern "C" __declspec(dllexport) PYINIT_DECL(vprof)();
extern "C" __declspec(dllexport) PYINIT_DECL(_srctests)();
extern "C" __declspec(dllexport) PYINIT_DECL(matchmaking)();
#else
extern "C" PYINIT_DECL(srcbuiltins)();
extern "C" PYINIT_DECL(_srcbase)();
extern "C" PYINIT_DECL(_vmath)();
extern "C" PYINIT_DECL(_filesystem)();
extern "C" PYINIT_DECL(_animation)();
extern "C" PYINIT_DECL(_entities)();
extern "C" PYINIT_DECL(_entitiesmisc)();
extern "C" PYINIT_DECL(_gameinterface)();
extern "C" PYINIT_DECL(_gamerules)();
extern "C" PYINIT_DECL(_utils)();
extern "C" PYINIT_DECL(_physics)();
extern "C" PYINIT_DECL(_sound)();
extern "C" PYINIT_DECL(_particles)();
extern "C" PYINIT_DECL(materials)();
extern "C" PYINIT_DECL(_te)();
extern "C" PYINIT_DECL(_fow)();
extern "C" PYINIT_DECL(unit_helper)();
extern "C" PYINIT_DECL(_editorsystem)();
extern "C" PYINIT_DECL(_steam)();
extern "C" PYINIT_DECL(_navmesh)();
extern "C" PYINIT_DECL(_recast)();
extern "C" PYINIT_DECL(_ndebugoverlay)();
extern "C" PYINIT_DECL(vprof)();
extern "C" PYINIT_DECL(_srctests)();
extern "C" PYINIT_DECL(matchmaking)();
#endif // _WIN32

// The append function
void AppendSharedModules()
{
	APPEND_MODULE(srcbuiltins)
	APPEND_MODULE(_srcbase)
	APPEND_MODULE(_vmath)
	APPEND_MODULE(_filesystem)
	APPEND_MODULE(_animation)
	APPEND_MODULE(_entities)
	APPEND_MODULE(_entitiesmisc)
	APPEND_MODULE(_gameinterface)
	APPEND_MODULE(_gamerules)
	APPEND_MODULE(_utils)
	APPEND_MODULE(_physics)
	APPEND_MODULE(_sound)
	APPEND_MODULE(_particles)
	APPEND_MODULE(materials)
	APPEND_MODULE(_te)
	APPEND_MODULE(_fow)
	APPEND_MODULE(unit_helper)
	APPEND_MODULE(_editorsystem)
	APPEND_MODULE(_steam)
	APPEND_MODULE(_navmesh)
	APPEND_MODULE(_recast)
	APPEND_MODULE(_ndebugoverlay)
	APPEND_MODULE(vprof)
	APPEND_MODULE(_srctests)
	APPEND_MODULE(matchmaking)
}
