// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef _gamerules_free_functions_hpp__pyplusplus_wrapper
#define _gamerules_free_functions_hpp__pyplusplus_wrapper

void _gamerules_register_free_functions();

#endif//_gamerules_free_functions_hpp__pyplusplus_wrapper

