// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#include "boost/python.hpp"
#include "cbase.h"
#include "mathlib/vmatrix.h"
#include "utlvector.h"
#include "shareddefs.h"
#include "util.h"
#include "takedamageinfo.h"
#include "baseanimating.h"
#include "BaseAnimatingOverlay.h"
#include "baseflex.h"
#include "basecombatcharacter.h"
#include "basegrenade_shared.h"
#include "player.h"
#include "hl2wars_player.h"
#include "unit_base_shared.h"
#include "unit_sense.h"
#include "wars_func_unit.h"
#include "soundent.h"
#include "gib.h"
#include "Sprite.h"
#include "SpriteTrail.h"
#include "smoke_trail.h"
#include "entityoutput.h"
#include "props.h"
#include "modelentities.h"
#include "triggers.h"
#include "wars_weapon.h"
#include "spark.h"
#include "physics_prop_ragdoll.h"
#include "filters.h"
#include "EntityFlame.h"
#include "shared_classnames.h"
#include "npcevent.h"
#include "studio.h"
#include "srcpy_entities.h"
#include "isaverestore.h"
#include "saverestore.h"
#include "mapentities_shared.h"
#include "vcollide_parse.h"
#include "hl2wars_player_shared.h"
#include "imouse.h"
#include "props_shared.h"
#include "beam_shared.h"
#include "basecombatweapon_shared.h"
#include "wars_mapboundary.h"
#include "srcpy_util.h"
#include "srcpy_converters_ents.h"
#include "srcpy.h"
#include "tier0/memdbgon.h"
#include "CBreakableProp_pypp.hpp"

namespace bp = boost::python;

struct CBreakableProp_wrapper : CBreakableProp, bp::wrapper< CBreakableProp > {

    CBreakableProp_wrapper( )
    : CBreakableProp( )
      , bp::wrapper< CBreakableProp >(){
        // null constructor
    
    }

    virtual void Event_Killed( ::CTakeDamageInfo const & info ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "Event_Killed: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling Event_Killed( boost::ref(info) ) of Class: CBreakableProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_Event_Killed = this->get_override( "Event_Killed" );
        if( func_Event_Killed.ptr() != Py_None )
            try {
                func_Event_Killed( boost::ref(info) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBreakableProp::Event_Killed( boost::ref(info) );
            }
        else
            this->CBreakableProp::Event_Killed( boost::ref(info) );
    }
    
    void default_Event_Killed( ::CTakeDamageInfo const & info ) {
        CBreakableProp::Event_Killed( boost::ref(info) );
    }

    virtual int OnTakeDamage( ::CTakeDamageInfo const & info ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "OnTakeDamage: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling OnTakeDamage( boost::ref(info) ) of Class: CBreakableProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_OnTakeDamage = this->get_override( "OnTakeDamage" );
        if( func_OnTakeDamage.ptr() != Py_None )
            try {
                return func_OnTakeDamage( boost::ref(info) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBreakableProp::OnTakeDamage( boost::ref(info) );
            }
        else
            return this->CBreakableProp::OnTakeDamage( boost::ref(info) );
    }
    
    int default_OnTakeDamage( ::CTakeDamageInfo const & info ) {
        return CBreakableProp::OnTakeDamage( boost::ref(info) );
    }

    virtual void Precache(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "Precache: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling Precache(  ) of Class: CBreakableProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_Precache = this->get_override( "Precache" );
        if( func_Precache.ptr() != Py_None )
            try {
                func_Precache(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBreakableProp::Precache(  );
            }
        else
            this->CBreakableProp::Precache(  );
    }
    
    void default_Precache(  ) {
        CBreakableProp::Precache( );
    }

    virtual void Spawn(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "Spawn: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling Spawn(  ) of Class: CBreakableProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_Spawn = this->get_override( "Spawn" );
        if( func_Spawn.ptr() != Py_None )
            try {
                func_Spawn(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBreakableProp::Spawn(  );
            }
        else
            this->CBreakableProp::Spawn(  );
    }
    
    void default_Spawn(  ) {
        CBreakableProp::Spawn( );
    }

    virtual void UpdateOnRemove(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "UpdateOnRemove: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling UpdateOnRemove(  ) of Class: CBreakableProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_UpdateOnRemove = this->get_override( "UpdateOnRemove" );
        if( func_UpdateOnRemove.ptr() != Py_None )
            try {
                func_UpdateOnRemove(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBreakableProp::UpdateOnRemove(  );
            }
        else
            this->CBreakableProp::UpdateOnRemove(  );
    }
    
    void default_UpdateOnRemove(  ) {
        CBreakableProp::UpdateOnRemove( );
    }

    virtual void Activate(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "Activate: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling Activate(  ) of Class: CBaseProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_Activate = this->get_override( "Activate" );
        if( func_Activate.ptr() != Py_None )
            try {
                func_Activate(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseProp::Activate(  );
            }
        else
            this->CBaseProp::Activate(  );
    }
    
    void default_Activate(  ) {
        CBaseProp::Activate( );
    }

    virtual bool CanBecomeRagdoll(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "CanBecomeRagdoll: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling CanBecomeRagdoll(  ) of Class: CBaseAnimating\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_CanBecomeRagdoll = this->get_override( "CanBecomeRagdoll" );
        if( func_CanBecomeRagdoll.ptr() != Py_None )
            try {
                return func_CanBecomeRagdoll(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseAnimating::CanBecomeRagdoll(  );
            }
        else
            return this->CBaseAnimating::CanBecomeRagdoll(  );
    }
    
    bool default_CanBecomeRagdoll(  ) {
        return CBaseAnimating::CanBecomeRagdoll( );
    }

    virtual void ComputeWorldSpaceSurroundingBox( ::Vector * pWorldMins, ::Vector * pWorldMaxs ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "ComputeWorldSpaceSurroundingBox: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling ComputeWorldSpaceSurroundingBox( boost::python::ptr(pWorldMins), boost::python::ptr(pWorldMaxs) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_ComputeWorldSpaceSurroundingBox = this->get_override( "ComputeWorldSpaceSurroundingBox" );
        if( func_ComputeWorldSpaceSurroundingBox.ptr() != Py_None )
            try {
                func_ComputeWorldSpaceSurroundingBox( boost::python::ptr(pWorldMins), boost::python::ptr(pWorldMaxs) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::ComputeWorldSpaceSurroundingBox( boost::python::ptr(pWorldMins), boost::python::ptr(pWorldMaxs) );
            }
        else
            this->CBaseEntity::ComputeWorldSpaceSurroundingBox( boost::python::ptr(pWorldMins), boost::python::ptr(pWorldMaxs) );
    }
    
    void default_ComputeWorldSpaceSurroundingBox( ::Vector * pWorldMins, ::Vector * pWorldMaxs ) {
        CBaseEntity::ComputeWorldSpaceSurroundingBox( boost::python::ptr(pWorldMins), boost::python::ptr(pWorldMaxs) );
    }

    virtual bool CreateVPhysics(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "CreateVPhysics: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling CreateVPhysics(  ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_CreateVPhysics = this->get_override( "CreateVPhysics" );
        if( func_CreateVPhysics.ptr() != Py_None )
            try {
                return func_CreateVPhysics(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::CreateVPhysics(  );
            }
        else
            return this->CBaseEntity::CreateVPhysics(  );
    }
    
    bool default_CreateVPhysics(  ) {
        return CBaseEntity::CreateVPhysics( );
    }

    virtual void DeathNotice( ::CBaseEntity * pVictim ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "DeathNotice: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling DeathNotice( boost::python::ptr(pVictim) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_DeathNotice = this->get_override( "DeathNotice" );
        if( func_DeathNotice.ptr() != Py_None )
            try {
                func_DeathNotice( boost::python::ptr(pVictim) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::DeathNotice( boost::python::ptr(pVictim) );
            }
        else
            this->CBaseEntity::DeathNotice( boost::python::ptr(pVictim) );
    }
    
    void default_DeathNotice( ::CBaseEntity * pVictim ) {
        CBaseEntity::DeathNotice( boost::python::ptr(pVictim) );
    }

    virtual void DoImpactEffect( ::trace_t & tr, int nDamageType ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "DoImpactEffect: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling DoImpactEffect( boost::ref(tr), nDamageType ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_DoImpactEffect = this->get_override( "DoImpactEffect" );
        if( func_DoImpactEffect.ptr() != Py_None )
            try {
                func_DoImpactEffect( boost::ref(tr), nDamageType );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::DoImpactEffect( boost::ref(tr), nDamageType );
            }
        else
            this->CBaseEntity::DoImpactEffect( boost::ref(tr), nDamageType );
    }
    
    void default_DoImpactEffect( ::trace_t & tr, int nDamageType ) {
        CBaseEntity::DoImpactEffect( boost::ref(tr), nDamageType );
    }

    virtual void DrawDebugGeometryOverlays(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "DrawDebugGeometryOverlays: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling DrawDebugGeometryOverlays(  ) of Class: CBaseProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_DrawDebugGeometryOverlays = this->get_override( "DrawDebugGeometryOverlays" );
        if( func_DrawDebugGeometryOverlays.ptr() != Py_None )
            try {
                func_DrawDebugGeometryOverlays(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseProp::DrawDebugGeometryOverlays(  );
            }
        else
            this->CBaseProp::DrawDebugGeometryOverlays(  );
    }
    
    void default_DrawDebugGeometryOverlays(  ) {
        CBaseProp::DrawDebugGeometryOverlays( );
    }

    virtual int DrawDebugTextOverlays(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "DrawDebugTextOverlays: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling DrawDebugTextOverlays(  ) of Class: CBaseAnimating\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_DrawDebugTextOverlays = this->get_override( "DrawDebugTextOverlays" );
        if( func_DrawDebugTextOverlays.ptr() != Py_None )
            try {
                return func_DrawDebugTextOverlays(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseAnimating::DrawDebugTextOverlays(  );
            }
        else
            return this->CBaseAnimating::DrawDebugTextOverlays(  );
    }
    
    int default_DrawDebugTextOverlays(  ) {
        return CBaseAnimating::DrawDebugTextOverlays( );
    }

    virtual void EndTouch( ::CBaseEntity * pOther ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "EndTouch: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling EndTouch( boost::python::ptr(pOther) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_EndTouch = this->get_override( "EndTouch" );
        if( func_EndTouch.ptr() != Py_None )
            try {
                func_EndTouch( boost::python::ptr(pOther) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::EndTouch( boost::python::ptr(pOther) );
            }
        else
            this->CBaseEntity::EndTouch( boost::python::ptr(pOther) );
    }
    
    void default_EndTouch( ::CBaseEntity * pOther ) {
        CBaseEntity::EndTouch( boost::python::ptr(pOther) );
    }

    virtual void Event_KilledOther( ::CBaseEntity * pVictim, ::CTakeDamageInfo const & info ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "Event_KilledOther: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling Event_KilledOther( boost::python::ptr(pVictim), boost::ref(info) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_Event_KilledOther = this->get_override( "Event_KilledOther" );
        if( func_Event_KilledOther.ptr() != Py_None )
            try {
                func_Event_KilledOther( boost::python::ptr(pVictim), boost::ref(info) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::Event_KilledOther( boost::python::ptr(pVictim), boost::ref(info) );
            }
        else
            this->CBaseEntity::Event_KilledOther( boost::python::ptr(pVictim), boost::ref(info) );
    }
    
    void default_Event_KilledOther( ::CBaseEntity * pVictim, ::CTakeDamageInfo const & info ) {
        CBaseEntity::Event_KilledOther( boost::python::ptr(pVictim), boost::ref(info) );
    }

    virtual ::IMouse * GetIMouse(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "GetIMouse: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling GetIMouse(  ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_GetIMouse = this->get_override( "GetIMouse" );
        if( func_GetIMouse.ptr() != Py_None )
            try {
                return func_GetIMouse(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::GetIMouse(  );
            }
        else
            return this->CBaseEntity::GetIMouse(  );
    }
    
    ::IMouse * default_GetIMouse(  ) {
        return CBaseEntity::GetIMouse( );
    }

    virtual char const * GetTracerType(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "GetTracerType: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling GetTracerType(  ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_GetTracerType = this->get_override( "GetTracerType" );
        if( func_GetTracerType.ptr() != Py_None )
            try {
                return func_GetTracerType(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::GetTracerType(  );
            }
        else
            return this->CBaseEntity::GetTracerType(  );
    }
    
    char const * default_GetTracerType(  ) {
        return CBaseEntity::GetTracerType( );
    }

    virtual bool KeyValue( char const * szKeyName, float flValue ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "KeyValue: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling KeyValue( szKeyName, flValue ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, flValue );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::KeyValue( szKeyName, flValue );
            }
        else
            return this->CBaseEntity::KeyValue( szKeyName, flValue );
    }
    
    bool default_KeyValue( char const * szKeyName, float flValue ) {
        return CBaseEntity::KeyValue( szKeyName, flValue );
    }

    virtual bool KeyValue( char const * szKeyName, int nValue ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "KeyValue: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling KeyValue( szKeyName, nValue ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, nValue );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::KeyValue( szKeyName, nValue );
            }
        else
            return this->CBaseEntity::KeyValue( szKeyName, nValue );
    }
    
    bool default_KeyValue( char const * szKeyName, int nValue ) {
        return CBaseEntity::KeyValue( szKeyName, nValue );
    }

    virtual bool KeyValue( char const * szKeyName, ::Vector const & vecValue ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "KeyValue: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling KeyValue( szKeyName, boost::ref(vecValue) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, boost::ref(vecValue) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::KeyValue( szKeyName, boost::ref(vecValue) );
            }
        else
            return this->CBaseEntity::KeyValue( szKeyName, boost::ref(vecValue) );
    }
    
    bool default_KeyValue( char const * szKeyName, ::Vector const & vecValue ) {
        return CBaseEntity::KeyValue( szKeyName, boost::ref(vecValue) );
    }

    virtual bool KeyValue( char const * szKeyName, char const * szValue ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "KeyValue: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling KeyValue( szKeyName, szValue ) of Class: CBaseProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, szValue );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseProp::KeyValue( szKeyName, szValue );
            }
        else
            return this->CBaseProp::KeyValue( szKeyName, szValue );
    }
    
    bool default_KeyValue( char const * szKeyName, char const * szValue ) {
        return CBaseProp::KeyValue( szKeyName, szValue );
    }

    virtual void MakeTracer( ::Vector const & vecTracerSrc, ::trace_t const & tr, int iTracerType ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "MakeTracer: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling MakeTracer( boost::ref(vecTracerSrc), boost::ref(tr), iTracerType ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_MakeTracer = this->get_override( "MakeTracer" );
        if( func_MakeTracer.ptr() != Py_None )
            try {
                func_MakeTracer( boost::ref(vecTracerSrc), boost::ref(tr), iTracerType );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::MakeTracer( boost::ref(vecTracerSrc), boost::ref(tr), iTracerType );
            }
        else
            this->CBaseEntity::MakeTracer( boost::ref(vecTracerSrc), boost::ref(tr), iTracerType );
    }
    
    void default_MakeTracer( ::Vector const & vecTracerSrc, ::trace_t const & tr, int iTracerType ) {
        CBaseEntity::MakeTracer( boost::ref(vecTracerSrc), boost::ref(tr), iTracerType );
    }

    virtual void ModifyOrAppendCriteria( ::ResponseRules::CriteriaSet & set ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "ModifyOrAppendCriteria: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling ModifyOrAppendCriteria( boost::ref(set) ) of Class: CBaseAnimating\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_ModifyOrAppendCriteria = this->get_override( "ModifyOrAppendCriteria" );
        if( func_ModifyOrAppendCriteria.ptr() != Py_None )
            try {
                func_ModifyOrAppendCriteria( boost::ref(set) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseAnimating::ModifyOrAppendCriteria( boost::ref(set) );
            }
        else
            this->CBaseAnimating::ModifyOrAppendCriteria( boost::ref(set) );
    }
    
    void default_ModifyOrAppendCriteria( ::ResponseRules::CriteriaSet & set ) {
        CBaseAnimating::ModifyOrAppendCriteria( boost::ref(set) );
    }

    virtual void OnChangeOwnerNumber( int old_owner_number ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "OnChangeOwnerNumber: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling OnChangeOwnerNumber( old_owner_number ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_OnChangeOwnerNumber = this->get_override( "OnChangeOwnerNumber" );
        if( func_OnChangeOwnerNumber.ptr() != Py_None )
            try {
                func_OnChangeOwnerNumber( old_owner_number );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::OnChangeOwnerNumber( old_owner_number );
            }
        else
            this->CBaseEntity::OnChangeOwnerNumber( old_owner_number );
    }
    
    void default_OnChangeOwnerNumber( int old_owner_number ) {
        CBaseEntity::OnChangeOwnerNumber( old_owner_number );
    }

    virtual void OnRestore(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "OnRestore: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling OnRestore(  ) of Class: CBaseAnimating\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_OnRestore = this->get_override( "OnRestore" );
        if( func_OnRestore.ptr() != Py_None )
            try {
                func_OnRestore(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseAnimating::OnRestore(  );
            }
        else
            this->CBaseAnimating::OnRestore(  );
    }
    
    void default_OnRestore(  ) {
        CBaseAnimating::OnRestore( );
    }

    virtual void OnSequenceSet( int nOldSequence ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "OnSequenceSet: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling OnSequenceSet( nOldSequence ) of Class: CBaseAnimating\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_OnSequenceSet = this->get_override( "OnSequenceSet" );
        if( func_OnSequenceSet.ptr() != Py_None )
            try {
                func_OnSequenceSet( nOldSequence );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseAnimating::OnSequenceSet( nOldSequence );
            }
        else
            this->CBaseAnimating::OnSequenceSet( nOldSequence );
    }
    
    void default_OnSequenceSet( int nOldSequence ) {
        CBaseAnimating::OnSequenceSet( nOldSequence );
    }

    virtual bool PassesDamageFilter( ::CTakeDamageInfo const & info ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "PassesDamageFilter: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling PassesDamageFilter( boost::ref(info) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_PassesDamageFilter = this->get_override( "PassesDamageFilter" );
        if( func_PassesDamageFilter.ptr() != Py_None )
            try {
                return func_PassesDamageFilter( boost::ref(info) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::PassesDamageFilter( boost::ref(info) );
            }
        else
            return this->CBaseEntity::PassesDamageFilter( boost::ref(info) );
    }
    
    bool default_PassesDamageFilter( ::CTakeDamageInfo const & info ) {
        return CBaseEntity::PassesDamageFilter( boost::ref(info) );
    }

    virtual void PostClientActive(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "PostClientActive: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling PostClientActive(  ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_PostClientActive = this->get_override( "PostClientActive" );
        if( func_PostClientActive.ptr() != Py_None )
            try {
                func_PostClientActive(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::PostClientActive(  );
            }
        else
            this->CBaseEntity::PostClientActive(  );
    }
    
    void default_PostClientActive(  ) {
        CBaseEntity::PostClientActive( );
    }

    virtual void PostConstructor( char const * szClassname ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "PostConstructor: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling PostConstructor( szClassname ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_PostConstructor = this->get_override( "PostConstructor" );
        if( func_PostConstructor.ptr() != Py_None )
            try {
                func_PostConstructor( szClassname );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::PostConstructor( szClassname );
            }
        else
            this->CBaseEntity::PostConstructor( szClassname );
    }
    
    void default_PostConstructor( char const * szClassname ) {
        CBaseEntity::PostConstructor( szClassname );
    }

    virtual void PyOnNewModel(  ){
        bp::override func_OnNewModel = this->get_override( "OnNewModel" );
        if( func_OnNewModel.ptr() != Py_None )
            try {
                func_OnNewModel(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseAnimating::PyOnNewModel(  );
            }
        else
            this->CBaseAnimating::PyOnNewModel(  );
    }
    
    virtual void default_OnNewModel(  ){
        CBaseAnimating::PyOnNewModel( );
    }

    virtual void StartTouch( ::CBaseEntity * pOther ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "StartTouch: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling StartTouch( boost::python::ptr(pOther) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_StartTouch = this->get_override( "StartTouch" );
        if( func_StartTouch.ptr() != Py_None )
            try {
                func_StartTouch( boost::python::ptr(pOther) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::StartTouch( boost::python::ptr(pOther) );
            }
        else
            this->CBaseEntity::StartTouch( boost::python::ptr(pOther) );
    }
    
    void default_StartTouch( ::CBaseEntity * pOther ) {
        CBaseEntity::StartTouch( boost::python::ptr(pOther) );
    }

    virtual void StopLoopingSounds(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "StopLoopingSounds: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling StopLoopingSounds(  ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_StopLoopingSounds = this->get_override( "StopLoopingSounds" );
        if( func_StopLoopingSounds.ptr() != Py_None )
            try {
                func_StopLoopingSounds(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::StopLoopingSounds(  );
            }
        else
            this->CBaseEntity::StopLoopingSounds(  );
    }
    
    void default_StopLoopingSounds(  ) {
        CBaseEntity::StopLoopingSounds( );
    }

    void TraceAttack( ::CTakeDamageInfo const & info, ::Vector const & vecDir, ::trace_t * ptr ){
        CBaseEntity::TraceAttack( boost::ref(info), boost::ref(vecDir), boost::python::ptr(ptr) );
    }

    virtual int UpdateTransmitState(  ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "UpdateTransmitState: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling UpdateTransmitState(  ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_UpdateTransmitState = this->get_override( "UpdateTransmitState" );
        if( func_UpdateTransmitState.ptr() != Py_None )
            try {
                return func_UpdateTransmitState(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->CBaseEntity::UpdateTransmitState(  );
            }
        else
            return this->CBaseEntity::UpdateTransmitState(  );
    }
    
    int default_UpdateTransmitState(  ) {
        return CBaseEntity::UpdateTransmitState( );
    }

    virtual void VPhysicsCollision( int index, ::gamevcollisionevent_t * pEvent ) {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( SrcPySystem()->IsPythonRunning() );
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "VPhysicsCollision: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling VPhysicsCollision( index, boost::python::ptr(pEvent) ) of Class: CBaseEntity\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        bp::override func_VPhysicsCollision = this->get_override( "VPhysicsCollision" );
        if( func_VPhysicsCollision.ptr() != Py_None )
            try {
                func_VPhysicsCollision( index, boost::python::ptr(pEvent) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->CBaseEntity::VPhysicsCollision( index, boost::python::ptr(pEvent) );
            }
        else
            this->CBaseEntity::VPhysicsCollision( index, boost::python::ptr(pEvent) );
    }
    
    void default_VPhysicsCollision( int index, ::gamevcollisionevent_t * pEvent ) {
        CBaseEntity::VPhysicsCollision( index, boost::python::ptr(pEvent) );
    }

    virtual ServerClass* GetServerClass() {
        #if defined(_WIN32)
        #if defined(_DEBUG)
        Assert( GetCurrentThreadId() == g_hPythonThreadID );
        #elif defined(PY_CHECKTHREADID)
        if( GetCurrentThreadId() != g_hPythonThreadID )
            Error( "GetServerClass: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
        #endif // _DEBUG/PY_CHECKTHREADID
        #endif // _WIN32
        #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
        if( py_log_overrides.GetBool() )
            Msg("Calling GetServerClass(  ) of Class: CBreakableProp\n");
        #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
        ServerClass *pServerClass = SrcPySystem()->Get<ServerClass *>("pyServerClass", GetPyInstance(), NULL, true);
        if( pServerClass )
            return pServerClass;
        return CBreakableProp::GetServerClass();
    }

    virtual PyObject *GetPySelf() const { return bp::detail::wrapper_base_::get_owner(*this); }

    virtual bool TestCollision( ::Ray_t const & ray, unsigned int mask, ::trace_t & trace ) {
                #if defined(_WIN32)
                #if defined(_DEBUG)
                Assert( GetCurrentThreadId() == g_hPythonThreadID );
                #elif defined(PY_CHECKTHREADID)
                if( GetCurrentThreadId() != g_hPythonThreadID )
                    Error( "TestCollision: Client? %d. Thread ID is not the same as in which the python interpreter is initialized! %d != %d. Tell a developer.\n", CBaseEntity::IsClient(), g_hPythonThreadID, GetCurrentThreadId() );
                #endif // _DEBUG/PY_CHECKTHREADID
                #endif // _WIN32
                #if defined(_DEBUG) || defined(PY_CHECK_LOG_OVERRIDES)
                if( py_log_overrides.GetBool() )
                    Msg("Calling TestCollision( boost::ref(ray), mask, boost::ref(trace) ) of Class: CBreakableProp\n");
                #endif // _DEBUG/PY_CHECK_LOG_OVERRIDES
                bp::override func_TestCollision = this->get_override( "TestCollision" );
                if( func_TestCollision.ptr() != Py_None )
                    try {
                        return func_TestCollision( PyRay_t(ray), mask, boost::ref(trace) );
                    } catch(bp::error_already_set &) {
                        PyErr_Print();
                        return this->CBreakableProp::TestCollision( boost::ref(ray), mask, boost::ref(trace) );
                    }
                else
                    return this->CBreakableProp::TestCollision( boost::ref(ray), mask, boost::ref(trace) );
            }
            
            bool default_TestCollision( ::Ray_t const & ray, unsigned int mask, ::trace_t & trace ) {
                return CBreakableProp::TestCollision( boost::ref(ray), mask, boost::ref(trace) );
            }

};

void register_CBreakableProp_class(){

    { //::CBreakableProp
        typedef bp::class_< CBreakableProp_wrapper, bp::bases< CBaseProp >, boost::noncopyable > CBreakableProp_exposer_t;
        CBreakableProp_exposer_t CBreakableProp_exposer = CBreakableProp_exposer_t( "CBreakableProp", bp::no_init );
        bp::scope CBreakableProp_scope( CBreakableProp_exposer );
        CBreakableProp_exposer.def( bp::init< >() );
        { //::CBreakableProp::AnimateThink
        
            typedef void ( ::CBreakableProp::*AnimateThink_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "AnimateThink"
                , AnimateThink_function_type( &::CBreakableProp::AnimateThink ) );
        
        }
        { //::CBreakableProp::Break
        
            typedef void ( ::CBreakableProp::*Break_function_type )( ::CBaseEntity *,::CTakeDamageInfo const & ) ;
            
            CBreakableProp_exposer.def( 
                "Break"
                , Break_function_type( &::CBreakableProp::Break )
                , ( bp::arg("pBreaker"), bp::arg("info") ) );
        
        }
        { //::CBreakableProp::BreakThink
        
            typedef void ( ::CBreakableProp::*BreakThink_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "BreakThink"
                , BreakThink_function_type( &::CBreakableProp::BreakThink ) );
        
        }
        { //::CBreakableProp::BreakablePropTouch
        
            typedef void ( ::CBreakableProp::*BreakablePropTouch_function_type )( ::CBaseEntity * ) ;
            
            CBreakableProp_exposer.def( 
                "BreakablePropTouch"
                , BreakablePropTouch_function_type( &::CBreakableProp::BreakablePropTouch )
                , ( bp::arg("pOther") ) );
        
        }
        { //::CBreakableProp::CopyFadeFrom
        
            typedef void ( ::CBreakableProp::*CopyFadeFrom_function_type )( ::CBreakableProp * ) ;
            
            CBreakableProp_exposer.def( 
                "CopyFadeFrom"
                , CopyFadeFrom_function_type( &::CBreakableProp::CopyFadeFrom )
                , ( bp::arg("pSource") ) );
        
        }
        { //::CBreakableProp::DisableAutoFade
        
            typedef void ( ::CBreakableProp::*DisableAutoFade_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "DisableAutoFade"
                , DisableAutoFade_function_type( &::CBreakableProp::DisableAutoFade ) );
        
        }
        { //::CBreakableProp::Event_Killed
        
            typedef void ( ::CBreakableProp::*Event_Killed_function_type )( ::CTakeDamageInfo const & ) ;
            typedef void ( CBreakableProp_wrapper::*default_Event_Killed_function_type )( ::CTakeDamageInfo const & ) ;
            
            CBreakableProp_exposer.def( 
                "Event_Killed"
                , Event_Killed_function_type(&::CBreakableProp::Event_Killed)
                , default_Event_Killed_function_type(&CBreakableProp_wrapper::default_Event_Killed)
                , ( bp::arg("info") ) );
        
        }
        { //::CBreakableProp::GetAutoAimRadius
        
            typedef float ( ::CBreakableProp::*GetAutoAimRadius_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetAutoAimRadius"
                , GetAutoAimRadius_function_type( &::CBreakableProp::GetAutoAimRadius ) );
        
        }
        { //::CBreakableProp::GetBasePropData
        
            typedef ::string_t ( ::CBreakableProp::*GetBasePropData_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetBasePropData"
                , GetBasePropData_function_type( &::CBreakableProp::GetBasePropData ) );
        
        }
        { //::CBreakableProp::GetBreakableCount
        
            typedef int ( ::CBreakableProp::*GetBreakableCount_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetBreakableCount"
                , GetBreakableCount_function_type( &::CBreakableProp::GetBreakableCount ) );
        
        }
        { //::CBreakableProp::GetBreakableModel
        
            typedef ::string_t ( ::CBreakableProp::*GetBreakableModel_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetBreakableModel"
                , GetBreakableModel_function_type( &::CBreakableProp::GetBreakableModel ) );
        
        }
        { //::CBreakableProp::GetBreakableSkin
        
            typedef int ( ::CBreakableProp::*GetBreakableSkin_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetBreakableSkin"
                , GetBreakableSkin_function_type( &::CBreakableProp::GetBreakableSkin ) );
        
        }
        { //::CBreakableProp::GetDmgModBullet
        
            typedef float ( ::CBreakableProp::*GetDmgModBullet_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetDmgModBullet"
                , GetDmgModBullet_function_type( &::CBreakableProp::GetDmgModBullet ) );
        
        }
        { //::CBreakableProp::GetDmgModClub
        
            typedef float ( ::CBreakableProp::*GetDmgModClub_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetDmgModClub"
                , GetDmgModClub_function_type( &::CBreakableProp::GetDmgModClub ) );
        
        }
        { //::CBreakableProp::GetDmgModExplosive
        
            typedef float ( ::CBreakableProp::*GetDmgModExplosive_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetDmgModExplosive"
                , GetDmgModExplosive_function_type( &::CBreakableProp::GetDmgModExplosive ) );
        
        }
        { //::CBreakableProp::GetDmgModFire
        
            typedef float ( ::CBreakableProp::*GetDmgModFire_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetDmgModFire"
                , GetDmgModFire_function_type( &::CBreakableProp::GetDmgModFire ) );
        
        }
        { //::CBreakableProp::GetExplosiveDamage
        
            typedef float ( ::CBreakableProp::*GetExplosiveDamage_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetExplosiveDamage"
                , GetExplosiveDamage_function_type( &::CBreakableProp::GetExplosiveDamage ) );
        
        }
        { //::CBreakableProp::GetExplosiveRadius
        
            typedef float ( ::CBreakableProp::*GetExplosiveRadius_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetExplosiveRadius"
                , GetExplosiveRadius_function_type( &::CBreakableProp::GetExplosiveRadius ) );
        
        }
        { //::CBreakableProp::GetMaxBreakableSize
        
            typedef int ( ::CBreakableProp::*GetMaxBreakableSize_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetMaxBreakableSize"
                , GetMaxBreakableSize_function_type( &::CBreakableProp::GetMaxBreakableSize ) );
        
        }
        { //::CBreakableProp::GetMultiplayerBreakMode
        
            typedef ::mp_break_t ( ::CBreakableProp::*GetMultiplayerBreakMode_function_type )(  ) const;
            
            CBreakableProp_exposer.def( 
                "GetMultiplayerBreakMode"
                , GetMultiplayerBreakMode_function_type( &::CBreakableProp::GetMultiplayerBreakMode ) );
        
        }
        { //::CBreakableProp::GetNumBreakableChunks
        
            typedef int ( ::CBreakableProp::*GetNumBreakableChunks_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetNumBreakableChunks"
                , GetNumBreakableChunks_function_type( &::CBreakableProp::GetNumBreakableChunks ) );
        
        }
        { //::CBreakableProp::GetPhysicsDamageTable
        
            typedef ::string_t ( ::CBreakableProp::*GetPhysicsDamageTable_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetPhysicsDamageTable"
                , GetPhysicsDamageTable_function_type( &::CBreakableProp::GetPhysicsDamageTable ) );
        
        }
        { //::CBreakableProp::GetPhysicsMode
        
            typedef int ( ::CBreakableProp::*GetPhysicsMode_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetPhysicsMode"
                , GetPhysicsMode_function_type( &::CBreakableProp::GetPhysicsMode ) );
        
        }
        { //::CBreakableProp::HandleFirstCollisionInteractions
        
            typedef void ( ::CBreakableProp::*HandleFirstCollisionInteractions_function_type )( int,::gamevcollisionevent_t * ) ;
            
            CBreakableProp_exposer.def( 
                "HandleFirstCollisionInteractions"
                , HandleFirstCollisionInteractions_function_type( &::CBreakableProp::HandleFirstCollisionInteractions )
                , ( bp::arg("index"), bp::arg("pEvent") ) );
        
        }
        { //::CBreakableProp::HandleInteractionStick
        
            typedef void ( ::CBreakableProp::*HandleInteractionStick_function_type )( int,::gamevcollisionevent_t * ) ;
            
            CBreakableProp_exposer.def( 
                "HandleInteractionStick"
                , HandleInteractionStick_function_type( &::CBreakableProp::HandleInteractionStick )
                , ( bp::arg("index"), bp::arg("pEvent") ) );
        
        }
        { //::CBreakableProp::HasInteraction
        
            typedef bool ( ::CBreakableProp::*HasInteraction_function_type )( ::propdata_interactions_t ) ;
            
            CBreakableProp_exposer.def( 
                "HasInteraction"
                , HasInteraction_function_type( &::CBreakableProp::HasInteraction )
                , ( bp::arg("Interaction") ) );
        
        }
        { //::CBreakableProp::HasPhysicsAttacker
        
            typedef ::CBasePlayer * ( ::CBreakableProp::*HasPhysicsAttacker_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "HasPhysicsAttacker"
                , HasPhysicsAttacker_function_type( &::CBreakableProp::HasPhysicsAttacker )
                , ( bp::arg("dt") )
                , bp::return_value_policy< bp::return_by_value >() );
        
        }
        { //::CBreakableProp::HasPreferredCarryAnglesForPlayer
        
            typedef bool ( ::CBreakableProp::*HasPreferredCarryAnglesForPlayer_function_type )( ::CBasePlayer * ) ;
            
            CBreakableProp_exposer.def( 
                "HasPreferredCarryAnglesForPlayer"
                , HasPreferredCarryAnglesForPlayer_function_type( &::CBreakableProp::HasPreferredCarryAnglesForPlayer )
                , ( bp::arg("pPlayer") ) );
        
        }
        { //::CBreakableProp::Ignite
        
            typedef void ( ::CBreakableProp::*Ignite_function_type )( float,bool,float,bool ) ;
            
            CBreakableProp_exposer.def( 
                "Ignite"
                , Ignite_function_type( &::CBreakableProp::Ignite )
                , ( bp::arg("flFlameLifetime"), bp::arg("bNPCOnly"), bp::arg("flSize")=0.0f, bp::arg("bCalledByLevelDesigner")=(bool)(false) ) );
        
        }
        { //::CBreakableProp::InputAddHealth
        
            typedef void ( ::CBreakableProp::*InputAddHealth_function_type )( ::inputdata_t & ) ;
            
            CBreakableProp_exposer.def( 
                "InputAddHealth"
                , InputAddHealth_function_type( &::CBreakableProp::InputAddHealth )
                , ( bp::arg("inputdata") ) );
        
        }
        { //::CBreakableProp::InputBreak
        
            typedef void ( ::CBreakableProp::*InputBreak_function_type )( ::inputdata_t & ) ;
            
            CBreakableProp_exposer.def( 
                "InputBreak"
                , InputBreak_function_type( &::CBreakableProp::InputBreak )
                , ( bp::arg("inputdata") ) );
        
        }
        { //::CBreakableProp::InputRemoveHealth
        
            typedef void ( ::CBreakableProp::*InputRemoveHealth_function_type )( ::inputdata_t & ) ;
            
            CBreakableProp_exposer.def( 
                "InputRemoveHealth"
                , InputRemoveHealth_function_type( &::CBreakableProp::InputRemoveHealth )
                , ( bp::arg("inputdata") ) );
        
        }
        { //::CBreakableProp::InputSetHealth
        
            typedef void ( ::CBreakableProp::*InputSetHealth_function_type )( ::inputdata_t & ) ;
            
            CBreakableProp_exposer.def( 
                "InputSetHealth"
                , InputSetHealth_function_type( &::CBreakableProp::InputSetHealth )
                , ( bp::arg("inputdata") ) );
        
        }
        { //::CBreakableProp::OnAttemptPhysGunPickup
        
            typedef bool ( ::CBreakableProp::*OnAttemptPhysGunPickup_function_type )( ::CBasePlayer *,::PhysGunPickup_t ) ;
            
            CBreakableProp_exposer.def( 
                "OnAttemptPhysGunPickup"
                , OnAttemptPhysGunPickup_function_type( &::CBreakableProp::OnAttemptPhysGunPickup )
                , ( bp::arg("pPhysGunUser"), bp::arg("reason") ) );
        
        }
        { //::CBreakableProp::OnPhysGunDrop
        
            typedef void ( ::CBreakableProp::*OnPhysGunDrop_function_type )( ::CBasePlayer *,::PhysGunDrop_t ) ;
            
            CBreakableProp_exposer.def( 
                "OnPhysGunDrop"
                , OnPhysGunDrop_function_type( &::CBreakableProp::OnPhysGunDrop )
                , ( bp::arg("pPhysGunUser"), bp::arg("reason") ) );
        
        }
        { //::CBreakableProp::OnPhysGunPickup
        
            typedef void ( ::CBreakableProp::*OnPhysGunPickup_function_type )( ::CBasePlayer *,::PhysGunPickup_t ) ;
            
            CBreakableProp_exposer.def( 
                "OnPhysGunPickup"
                , OnPhysGunPickup_function_type( &::CBreakableProp::OnPhysGunPickup )
                , ( bp::arg("pPhysGunUser"), bp::arg("reason") ) );
        
        }
        { //::CBreakableProp::OnTakeDamage
        
            typedef int ( ::CBreakableProp::*OnTakeDamage_function_type )( ::CTakeDamageInfo const & ) ;
            typedef int ( CBreakableProp_wrapper::*default_OnTakeDamage_function_type )( ::CTakeDamageInfo const & ) ;
            
            CBreakableProp_exposer.def( 
                "OnTakeDamage"
                , OnTakeDamage_function_type(&::CBreakableProp::OnTakeDamage)
                , default_OnTakeDamage_function_type(&CBreakableProp_wrapper::default_OnTakeDamage)
                , ( bp::arg("info") ) );
        
        }
        { //::CBreakableProp::OverridePropdata
        
            typedef bool ( ::CBreakableProp::*OverridePropdata_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "OverridePropdata"
                , OverridePropdata_function_type( &::CBreakableProp::OverridePropdata ) );
        
        }
        { //::CBreakableProp::PhysGunLaunchAngularImpulse
        
            typedef ::AngularImpulse ( ::CBreakableProp::*PhysGunLaunchAngularImpulse_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "PhysGunLaunchAngularImpulse"
                , PhysGunLaunchAngularImpulse_function_type( &::CBreakableProp::PhysGunLaunchAngularImpulse ) );
        
        }
        { //::CBreakableProp::PlayPuntSound
        
            typedef void ( ::CBreakableProp::*PlayPuntSound_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "PlayPuntSound"
                , PlayPuntSound_function_type( &::CBreakableProp::PlayPuntSound ) );
        
        }
        { //::CBreakableProp::Precache
        
            typedef void ( ::CBreakableProp::*Precache_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_Precache_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "Precache"
                , Precache_function_type(&::CBreakableProp::Precache)
                , default_Precache_function_type(&CBreakableProp_wrapper::default_Precache) );
        
        }
        { //::CBreakableProp::PreferredCarryAngles
        
            typedef ::QAngle ( ::CBreakableProp::*PreferredCarryAngles_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "PreferredCarryAngles"
                , PreferredCarryAngles_function_type( &::CBreakableProp::PreferredCarryAngles ) );
        
        }
        { //::CBreakableProp::PropDataOverrodeAIWalkable
        
            typedef bool ( ::CBreakableProp::*PropDataOverrodeAIWalkable_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "PropDataOverrodeAIWalkable"
                , PropDataOverrodeAIWalkable_function_type( &::CBreakableProp::PropDataOverrodeAIWalkable ) );
        
        }
        { //::CBreakableProp::PropDataOverrodeBlockLOS
        
            typedef bool ( ::CBreakableProp::*PropDataOverrodeBlockLOS_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "PropDataOverrodeBlockLOS"
                , PropDataOverrodeBlockLOS_function_type( &::CBreakableProp::PropDataOverrodeBlockLOS ) );
        
        }
        { //::CBreakableProp::RemoveInteraction
        
            typedef void ( ::CBreakableProp::*RemoveInteraction_function_type )( ::propdata_interactions_t ) ;
            
            CBreakableProp_exposer.def( 
                "RemoveInteraction"
                , RemoveInteraction_function_type( &::CBreakableProp::RemoveInteraction )
                , ( bp::arg("Interaction") ) );
        
        }
        { //::CBreakableProp::SetBasePropData
        
            typedef void ( ::CBreakableProp::*SetBasePropData_function_type )( ::string_t ) ;
            
            CBreakableProp_exposer.def( 
                "SetBasePropData"
                , SetBasePropData_function_type( &::CBreakableProp::SetBasePropData )
                , ( bp::arg("iszBase") ) );
        
        }
        { //::CBreakableProp::SetBreakableCount
        
            typedef void ( ::CBreakableProp::*SetBreakableCount_function_type )( int ) ;
            
            CBreakableProp_exposer.def( 
                "SetBreakableCount"
                , SetBreakableCount_function_type( &::CBreakableProp::SetBreakableCount )
                , ( bp::arg("iCount") ) );
        
        }
        { //::CBreakableProp::SetBreakableModel
        
            typedef void ( ::CBreakableProp::*SetBreakableModel_function_type )( ::string_t ) ;
            
            CBreakableProp_exposer.def( 
                "SetBreakableModel"
                , SetBreakableModel_function_type( &::CBreakableProp::SetBreakableModel )
                , ( bp::arg("iszModel") ) );
        
        }
        { //::CBreakableProp::SetBreakableSkin
        
            typedef void ( ::CBreakableProp::*SetBreakableSkin_function_type )( int ) ;
            
            CBreakableProp_exposer.def( 
                "SetBreakableSkin"
                , SetBreakableSkin_function_type( &::CBreakableProp::SetBreakableSkin )
                , ( bp::arg("iSkin") ) );
        
        }
        { //::CBreakableProp::SetDmgModBullet
        
            typedef void ( ::CBreakableProp::*SetDmgModBullet_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "SetDmgModBullet"
                , SetDmgModBullet_function_type( &::CBreakableProp::SetDmgModBullet )
                , ( bp::arg("flDmgMod") ) );
        
        }
        { //::CBreakableProp::SetDmgModClub
        
            typedef void ( ::CBreakableProp::*SetDmgModClub_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "SetDmgModClub"
                , SetDmgModClub_function_type( &::CBreakableProp::SetDmgModClub )
                , ( bp::arg("flDmgMod") ) );
        
        }
        { //::CBreakableProp::SetDmgModExplosive
        
            typedef void ( ::CBreakableProp::*SetDmgModExplosive_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "SetDmgModExplosive"
                , SetDmgModExplosive_function_type( &::CBreakableProp::SetDmgModExplosive )
                , ( bp::arg("flDmgMod") ) );
        
        }
        { //::CBreakableProp::SetDmgModFire
        
            typedef void ( ::CBreakableProp::*SetDmgModFire_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "SetDmgModFire"
                , SetDmgModFire_function_type( &::CBreakableProp::SetDmgModFire )
                , ( bp::arg("flDmgMod") ) );
        
        }
        { //::CBreakableProp::SetExplosiveDamage
        
            typedef void ( ::CBreakableProp::*SetExplosiveDamage_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "SetExplosiveDamage"
                , SetExplosiveDamage_function_type( &::CBreakableProp::SetExplosiveDamage )
                , ( bp::arg("flDamage") ) );
        
        }
        { //::CBreakableProp::SetExplosiveRadius
        
            typedef void ( ::CBreakableProp::*SetExplosiveRadius_function_type )( float ) ;
            
            CBreakableProp_exposer.def( 
                "SetExplosiveRadius"
                , SetExplosiveRadius_function_type( &::CBreakableProp::SetExplosiveRadius )
                , ( bp::arg("flRadius") ) );
        
        }
        { //::CBreakableProp::SetInteraction
        
            typedef void ( ::CBreakableProp::*SetInteraction_function_type )( ::propdata_interactions_t ) ;
            
            CBreakableProp_exposer.def( 
                "SetInteraction"
                , SetInteraction_function_type( &::CBreakableProp::SetInteraction )
                , ( bp::arg("Interaction") ) );
        
        }
        { //::CBreakableProp::SetMaxBreakableSize
        
            typedef void ( ::CBreakableProp::*SetMaxBreakableSize_function_type )( int ) ;
            
            CBreakableProp_exposer.def( 
                "SetMaxBreakableSize"
                , SetMaxBreakableSize_function_type( &::CBreakableProp::SetMaxBreakableSize )
                , ( bp::arg("iSize") ) );
        
        }
        { //::CBreakableProp::SetMultiplayerBreakMode
        
            typedef void ( ::CBreakableProp::*SetMultiplayerBreakMode_function_type )( ::mp_break_t ) ;
            
            CBreakableProp_exposer.def( 
                "SetMultiplayerBreakMode"
                , SetMultiplayerBreakMode_function_type( &::CBreakableProp::SetMultiplayerBreakMode )
                , ( bp::arg("mode") ) );
        
        }
        { //::CBreakableProp::SetPhysicsAttacker
        
            typedef void ( ::CBreakableProp::*SetPhysicsAttacker_function_type )( ::CBasePlayer *,float ) ;
            
            CBreakableProp_exposer.def( 
                "SetPhysicsAttacker"
                , SetPhysicsAttacker_function_type( &::CBreakableProp::SetPhysicsAttacker )
                , ( bp::arg("pEntity"), bp::arg("flTime") ) );
        
        }
        { //::CBreakableProp::SetPhysicsDamageTable
        
            typedef void ( ::CBreakableProp::*SetPhysicsDamageTable_function_type )( ::string_t ) ;
            
            CBreakableProp_exposer.def( 
                "SetPhysicsDamageTable"
                , SetPhysicsDamageTable_function_type( &::CBreakableProp::SetPhysicsDamageTable )
                , ( bp::arg("iszTableName") ) );
        
        }
        { //::CBreakableProp::SetPhysicsMode
        
            typedef void ( ::CBreakableProp::*SetPhysicsMode_function_type )( int ) ;
            
            CBreakableProp_exposer.def( 
                "SetPhysicsMode"
                , SetPhysicsMode_function_type( &::CBreakableProp::SetPhysicsMode )
                , ( bp::arg("iMode") ) );
        
        }
        { //::CBreakableProp::SetPropDataBlocksLOS
        
            typedef void ( ::CBreakableProp::*SetPropDataBlocksLOS_function_type )( bool ) ;
            
            CBreakableProp_exposer.def( 
                "SetPropDataBlocksLOS"
                , SetPropDataBlocksLOS_function_type( &::CBreakableProp::SetPropDataBlocksLOS )
                , ( bp::arg("bBlocksLOS") ) );
        
        }
        { //::CBreakableProp::SetPropDataIsAIWalkable
        
            typedef void ( ::CBreakableProp::*SetPropDataIsAIWalkable_function_type )( bool ) ;
            
            CBreakableProp_exposer.def( 
                "SetPropDataIsAIWalkable"
                , SetPropDataIsAIWalkable_function_type( &::CBreakableProp::SetPropDataIsAIWalkable )
                , ( bp::arg("b") ) );
        
        }
        { //::CBreakableProp::Spawn
        
            typedef void ( ::CBreakableProp::*Spawn_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_Spawn_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "Spawn"
                , Spawn_function_type(&::CBreakableProp::Spawn)
                , default_Spawn_function_type(&CBreakableProp_wrapper::default_Spawn) );
        
        }
        { //::CBreakableProp::StickAtPosition
        
            typedef void ( ::CBreakableProp::*StickAtPosition_function_type )( ::Vector const &,::Vector const &,::QAngle const & ) ;
            
            CBreakableProp_exposer.def( 
                "StickAtPosition"
                , StickAtPosition_function_type( &::CBreakableProp::StickAtPosition )
                , ( bp::arg("stickPosition"), bp::arg("savePosition"), bp::arg("saveAngles") ) );
        
        }
        { //::CBreakableProp::UpdateOnRemove
        
            typedef void ( ::CBreakableProp::*UpdateOnRemove_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_UpdateOnRemove_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "UpdateOnRemove"
                , UpdateOnRemove_function_type(&::CBreakableProp::UpdateOnRemove)
                , default_UpdateOnRemove_function_type(&CBreakableProp_wrapper::default_UpdateOnRemove) );
        
        }
        CBreakableProp_exposer.def_readwrite( "m_OnBreak", &CBreakableProp::m_OnBreak );
        CBreakableProp_exposer.def_readwrite( "m_OnHealthChanged", &CBreakableProp::m_OnHealthChanged );
        CBreakableProp_exposer.def_readwrite( "m_OnTakeDamage", &CBreakableProp::m_OnTakeDamage );
        CBreakableProp_exposer.def_readwrite( "m_iMinHealthDmg", &CBreakableProp::m_iMinHealthDmg );
        CBreakableProp_exposer.def_readwrite( "m_impactEnergyScale", &CBreakableProp::m_impactEnergyScale );
        CBreakableProp_exposer.def_readwrite( "m_preferredCarryAngles", &CBreakableProp::m_preferredCarryAngles );
        { //::CBaseProp::Activate
        
            typedef void ( ::CBaseProp::*Activate_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_Activate_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "Activate"
                , Activate_function_type(&::CBaseProp::Activate)
                , default_Activate_function_type(&CBreakableProp_wrapper::default_Activate) );
        
        }
        { //::CBaseAnimating::CanBecomeRagdoll
        
            typedef bool ( ::CBaseAnimating::*CanBecomeRagdoll_function_type )(  ) ;
            typedef bool ( CBreakableProp_wrapper::*default_CanBecomeRagdoll_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "CanBecomeRagdoll"
                , CanBecomeRagdoll_function_type(&::CBaseAnimating::CanBecomeRagdoll)
                , default_CanBecomeRagdoll_function_type(&CBreakableProp_wrapper::default_CanBecomeRagdoll) );
        
        }
        { //::CBaseEntity::ComputeWorldSpaceSurroundingBox
        
            typedef void ( ::CBaseEntity::*ComputeWorldSpaceSurroundingBox_function_type )( ::Vector *,::Vector * ) ;
            typedef void ( CBreakableProp_wrapper::*default_ComputeWorldSpaceSurroundingBox_function_type )( ::Vector *,::Vector * ) ;
            
            CBreakableProp_exposer.def( 
                "ComputeWorldSpaceSurroundingBox"
                , ComputeWorldSpaceSurroundingBox_function_type(&::CBaseEntity::ComputeWorldSpaceSurroundingBox)
                , default_ComputeWorldSpaceSurroundingBox_function_type(&CBreakableProp_wrapper::default_ComputeWorldSpaceSurroundingBox)
                , ( bp::arg("pWorldMins"), bp::arg("pWorldMaxs") ) );
        
        }
        { //::CBaseEntity::CreateVPhysics
        
            typedef bool ( ::CBaseEntity::*CreateVPhysics_function_type )(  ) ;
            typedef bool ( CBreakableProp_wrapper::*default_CreateVPhysics_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "CreateVPhysics"
                , CreateVPhysics_function_type(&::CBaseEntity::CreateVPhysics)
                , default_CreateVPhysics_function_type(&CBreakableProp_wrapper::default_CreateVPhysics) );
        
        }
        { //::CBaseEntity::DeathNotice
        
            typedef void ( ::CBaseEntity::*DeathNotice_function_type )( ::CBaseEntity * ) ;
            typedef void ( CBreakableProp_wrapper::*default_DeathNotice_function_type )( ::CBaseEntity * ) ;
            
            CBreakableProp_exposer.def( 
                "DeathNotice"
                , DeathNotice_function_type(&::CBaseEntity::DeathNotice)
                , default_DeathNotice_function_type(&CBreakableProp_wrapper::default_DeathNotice)
                , ( bp::arg("pVictim") ) );
        
        }
        { //::CBaseEntity::DoImpactEffect
        
            typedef void ( ::CBaseEntity::*DoImpactEffect_function_type )( ::trace_t &,int ) ;
            typedef void ( CBreakableProp_wrapper::*default_DoImpactEffect_function_type )( ::trace_t &,int ) ;
            
            CBreakableProp_exposer.def( 
                "DoImpactEffect"
                , DoImpactEffect_function_type(&::CBaseEntity::DoImpactEffect)
                , default_DoImpactEffect_function_type(&CBreakableProp_wrapper::default_DoImpactEffect)
                , ( bp::arg("tr"), bp::arg("nDamageType") ) );
        
        }
        { //::CBaseProp::DrawDebugGeometryOverlays
        
            typedef void ( ::CBaseProp::*DrawDebugGeometryOverlays_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_DrawDebugGeometryOverlays_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "DrawDebugGeometryOverlays"
                , DrawDebugGeometryOverlays_function_type(&::CBaseProp::DrawDebugGeometryOverlays)
                , default_DrawDebugGeometryOverlays_function_type(&CBreakableProp_wrapper::default_DrawDebugGeometryOverlays) );
        
        }
        { //::CBaseAnimating::DrawDebugTextOverlays
        
            typedef int ( ::CBaseAnimating::*DrawDebugTextOverlays_function_type )(  ) ;
            typedef int ( CBreakableProp_wrapper::*default_DrawDebugTextOverlays_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "DrawDebugTextOverlays"
                , DrawDebugTextOverlays_function_type(&::CBaseAnimating::DrawDebugTextOverlays)
                , default_DrawDebugTextOverlays_function_type(&CBreakableProp_wrapper::default_DrawDebugTextOverlays) );
        
        }
        { //::CBaseEntity::EndTouch
        
            typedef void ( ::CBaseEntity::*EndTouch_function_type )( ::CBaseEntity * ) ;
            typedef void ( CBreakableProp_wrapper::*default_EndTouch_function_type )( ::CBaseEntity * ) ;
            
            CBreakableProp_exposer.def( 
                "EndTouch"
                , EndTouch_function_type(&::CBaseEntity::EndTouch)
                , default_EndTouch_function_type(&CBreakableProp_wrapper::default_EndTouch)
                , ( bp::arg("pOther") ) );
        
        }
        { //::CBaseEntity::Event_KilledOther
        
            typedef void ( ::CBaseEntity::*Event_KilledOther_function_type )( ::CBaseEntity *,::CTakeDamageInfo const & ) ;
            typedef void ( CBreakableProp_wrapper::*default_Event_KilledOther_function_type )( ::CBaseEntity *,::CTakeDamageInfo const & ) ;
            
            CBreakableProp_exposer.def( 
                "Event_KilledOther"
                , Event_KilledOther_function_type(&::CBaseEntity::Event_KilledOther)
                , default_Event_KilledOther_function_type(&CBreakableProp_wrapper::default_Event_KilledOther)
                , ( bp::arg("pVictim"), bp::arg("info") ) );
        
        }
        { //::CBaseEntity::GetIMouse
        
            typedef ::IMouse * ( ::CBaseEntity::*GetIMouse_function_type )(  ) ;
            typedef ::IMouse * ( CBreakableProp_wrapper::*default_GetIMouse_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetIMouse"
                , GetIMouse_function_type(&::CBaseEntity::GetIMouse)
                , default_GetIMouse_function_type(&CBreakableProp_wrapper::default_GetIMouse)
                , bp::return_value_policy< bp::return_by_value >() );
        
        }
        { //::CBaseEntity::GetTracerType
        
            typedef char const * ( ::CBaseEntity::*GetTracerType_function_type )(  ) ;
            typedef char const * ( CBreakableProp_wrapper::*default_GetTracerType_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "GetTracerType"
                , GetTracerType_function_type(&::CBaseEntity::GetTracerType)
                , default_GetTracerType_function_type(&CBreakableProp_wrapper::default_GetTracerType) );
        
        }
        { //::CBaseEntity::KeyValue
        
            typedef bool ( ::CBaseEntity::*KeyValue_function_type )( char const *,float ) ;
            typedef bool ( CBreakableProp_wrapper::*default_KeyValue_function_type )( char const *,float ) ;
            
            CBreakableProp_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::CBaseEntity::KeyValue)
                , default_KeyValue_function_type(&CBreakableProp_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("flValue") ) );
        
        }
        { //::CBaseEntity::KeyValue
        
            typedef bool ( ::CBaseEntity::*KeyValue_function_type )( char const *,int ) ;
            typedef bool ( CBreakableProp_wrapper::*default_KeyValue_function_type )( char const *,int ) ;
            
            CBreakableProp_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::CBaseEntity::KeyValue)
                , default_KeyValue_function_type(&CBreakableProp_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("nValue") ) );
        
        }
        { //::CBaseEntity::KeyValue
        
            typedef bool ( ::CBaseEntity::*KeyValue_function_type )( char const *,::Vector const & ) ;
            typedef bool ( CBreakableProp_wrapper::*default_KeyValue_function_type )( char const *,::Vector const & ) ;
            
            CBreakableProp_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::CBaseEntity::KeyValue)
                , default_KeyValue_function_type(&CBreakableProp_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("vecValue") ) );
        
        }
        { //::CBaseProp::KeyValue
        
            typedef bool ( ::CBaseProp::*KeyValue_function_type )( char const *,char const * ) ;
            typedef bool ( CBreakableProp_wrapper::*default_KeyValue_function_type )( char const *,char const * ) ;
            
            CBreakableProp_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::CBaseProp::KeyValue)
                , default_KeyValue_function_type(&CBreakableProp_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("szValue") ) );
        
        }
        { //::CBaseEntity::MakeTracer
        
            typedef void ( ::CBaseEntity::*MakeTracer_function_type )( ::Vector const &,::trace_t const &,int ) ;
            typedef void ( CBreakableProp_wrapper::*default_MakeTracer_function_type )( ::Vector const &,::trace_t const &,int ) ;
            
            CBreakableProp_exposer.def( 
                "MakeTracer"
                , MakeTracer_function_type(&::CBaseEntity::MakeTracer)
                , default_MakeTracer_function_type(&CBreakableProp_wrapper::default_MakeTracer)
                , ( bp::arg("vecTracerSrc"), bp::arg("tr"), bp::arg("iTracerType") ) );
        
        }
        { //::CBaseAnimating::ModifyOrAppendCriteria
        
            typedef void ( ::CBaseAnimating::*ModifyOrAppendCriteria_function_type )( ::ResponseRules::CriteriaSet & ) ;
            typedef void ( CBreakableProp_wrapper::*default_ModifyOrAppendCriteria_function_type )( ::ResponseRules::CriteriaSet & ) ;
            
            CBreakableProp_exposer.def( 
                "ModifyOrAppendCriteria"
                , ModifyOrAppendCriteria_function_type(&::CBaseAnimating::ModifyOrAppendCriteria)
                , default_ModifyOrAppendCriteria_function_type(&CBreakableProp_wrapper::default_ModifyOrAppendCriteria)
                , ( bp::arg("set") ) );
        
        }
        { //::CBaseEntity::OnChangeOwnerNumber
        
            typedef void ( ::CBaseEntity::*OnChangeOwnerNumber_function_type )( int ) ;
            typedef void ( CBreakableProp_wrapper::*default_OnChangeOwnerNumber_function_type )( int ) ;
            
            CBreakableProp_exposer.def( 
                "OnChangeOwnerNumber"
                , OnChangeOwnerNumber_function_type(&::CBaseEntity::OnChangeOwnerNumber)
                , default_OnChangeOwnerNumber_function_type(&CBreakableProp_wrapper::default_OnChangeOwnerNumber)
                , ( bp::arg("old_owner_number") ) );
        
        }
        { //::CBaseAnimating::OnRestore
        
            typedef void ( ::CBaseAnimating::*OnRestore_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_OnRestore_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "OnRestore"
                , OnRestore_function_type(&::CBaseAnimating::OnRestore)
                , default_OnRestore_function_type(&CBreakableProp_wrapper::default_OnRestore) );
        
        }
        { //::CBaseAnimating::OnSequenceSet
        
            typedef void ( ::CBaseAnimating::*OnSequenceSet_function_type )( int ) ;
            typedef void ( CBreakableProp_wrapper::*default_OnSequenceSet_function_type )( int ) ;
            
            CBreakableProp_exposer.def( 
                "OnSequenceSet"
                , OnSequenceSet_function_type(&::CBaseAnimating::OnSequenceSet)
                , default_OnSequenceSet_function_type(&CBreakableProp_wrapper::default_OnSequenceSet)
                , ( bp::arg("nOldSequence") ) );
        
        }
        { //::CBaseEntity::PassesDamageFilter
        
            typedef bool ( ::CBaseEntity::*PassesDamageFilter_function_type )( ::CTakeDamageInfo const & ) ;
            typedef bool ( CBreakableProp_wrapper::*default_PassesDamageFilter_function_type )( ::CTakeDamageInfo const & ) ;
            
            CBreakableProp_exposer.def( 
                "PassesDamageFilter"
                , PassesDamageFilter_function_type(&::CBaseEntity::PassesDamageFilter)
                , default_PassesDamageFilter_function_type(&CBreakableProp_wrapper::default_PassesDamageFilter)
                , ( bp::arg("info") ) );
        
        }
        { //::CBaseEntity::PostClientActive
        
            typedef void ( ::CBaseEntity::*PostClientActive_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_PostClientActive_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "PostClientActive"
                , PostClientActive_function_type(&::CBaseEntity::PostClientActive)
                , default_PostClientActive_function_type(&CBreakableProp_wrapper::default_PostClientActive) );
        
        }
        { //::CBaseEntity::PostConstructor
        
            typedef void ( ::CBaseEntity::*PostConstructor_function_type )( char const * ) ;
            typedef void ( CBreakableProp_wrapper::*default_PostConstructor_function_type )( char const * ) ;
            
            CBreakableProp_exposer.def( 
                "PostConstructor"
                , PostConstructor_function_type(&::CBaseEntity::PostConstructor)
                , default_PostConstructor_function_type(&CBreakableProp_wrapper::default_PostConstructor)
                , ( bp::arg("szClassname") ) );
        
        }
        { //::CBaseAnimating::PyOnNewModel
        
            typedef void ( CBreakableProp_wrapper::*OnNewModel_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "OnNewModel"
                , OnNewModel_function_type( &CBreakableProp_wrapper::default_OnNewModel ) );
        
        }
        { //::CBaseEntity::StartTouch
        
            typedef void ( ::CBaseEntity::*StartTouch_function_type )( ::CBaseEntity * ) ;
            typedef void ( CBreakableProp_wrapper::*default_StartTouch_function_type )( ::CBaseEntity * ) ;
            
            CBreakableProp_exposer.def( 
                "StartTouch"
                , StartTouch_function_type(&::CBaseEntity::StartTouch)
                , default_StartTouch_function_type(&CBreakableProp_wrapper::default_StartTouch)
                , ( bp::arg("pOther") ) );
        
        }
        { //::CBaseEntity::StopLoopingSounds
        
            typedef void ( ::CBaseEntity::*StopLoopingSounds_function_type )(  ) ;
            typedef void ( CBreakableProp_wrapper::*default_StopLoopingSounds_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "StopLoopingSounds"
                , StopLoopingSounds_function_type(&::CBaseEntity::StopLoopingSounds)
                , default_StopLoopingSounds_function_type(&CBreakableProp_wrapper::default_StopLoopingSounds) );
        
        }
        { //::CBaseEntity::TraceAttack
        
            typedef void ( CBreakableProp_wrapper::*TraceAttack_function_type )( ::CTakeDamageInfo const &,::Vector const &,::trace_t * ) ;
            
            CBreakableProp_exposer.def( 
                "TraceAttack"
                , TraceAttack_function_type( &CBreakableProp_wrapper::TraceAttack )
                , ( bp::arg("info"), bp::arg("vecDir"), bp::arg("ptr") ) );
        
        }
        { //::CBaseEntity::UpdateTransmitState
        
            typedef int ( ::CBaseEntity::*UpdateTransmitState_function_type )(  ) ;
            typedef int ( CBreakableProp_wrapper::*default_UpdateTransmitState_function_type )(  ) ;
            
            CBreakableProp_exposer.def( 
                "UpdateTransmitState"
                , UpdateTransmitState_function_type(&::CBaseEntity::UpdateTransmitState)
                , default_UpdateTransmitState_function_type(&CBreakableProp_wrapper::default_UpdateTransmitState) );
        
        }
        { //::CBaseEntity::VPhysicsCollision
        
            typedef void ( ::CBaseEntity::*VPhysicsCollision_function_type )( int,::gamevcollisionevent_t * ) ;
            typedef void ( CBreakableProp_wrapper::*default_VPhysicsCollision_function_type )( int,::gamevcollisionevent_t * ) ;
            
            CBreakableProp_exposer.def( 
                "VPhysicsCollision"
                , VPhysicsCollision_function_type(&::CBaseEntity::VPhysicsCollision)
                , default_VPhysicsCollision_function_type(&CBreakableProp_wrapper::default_VPhysicsCollision)
                , ( bp::arg("index"), bp::arg("pEvent") ) );
        
        }
        { //::CBreakableProp::TestCollision
            
                typedef bool ( ::CBreakableProp::*TestCollision_function_type )( ::Ray_t const &,unsigned int,::trace_t & ) ;
                typedef bool ( CBreakableProp_wrapper::*default_TestCollision_function_type )( ::Ray_t const &,unsigned int,::trace_t & ) ;

                CBreakableProp_exposer.def( 
                    "TestCollision"
                    , TestCollision_function_type(&::CBreakableProp::TestCollision)
                    , default_TestCollision_function_type(&CBreakableProp_wrapper::default_TestCollision)
                    , ( bp::arg("ray"), bp::arg("mask"), bp::arg("trace") ) );

            }
    }

}

