// This file has been generated by Py++.

#ifndef PyBaseVGUIHandle_hpp__pyplusplus_wrapper
#define PyBaseVGUIHandle_hpp__pyplusplus_wrapper

void register_PyBaseVGUIHandle_class();

#endif//PyBaseVGUIHandle_hpp__pyplusplus_wrapper
