// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CGameRules_hpp__pyplusplus_wrapper
#define CGameRules_hpp__pyplusplus_wrapper

void register_CGameRules_class();

#endif//CGameRules_hpp__pyplusplus_wrapper

